version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: mav-bittrack_server_1
      APP_PORT: 8585

  server:
    image: ghcr.io/maverick-2009/bittrack:1.1.0@sha256:b6bec6f4cf50e23459a22030dd81f2249bd1d576fd7d4922b4d0c31314f69865
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DATA_DIR: "/app/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
