version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: mav-bittrack_server_1
      APP_PORT: 8585
  server:
    image: ghcr.io/maverick-2009/bittrack:1.0.0@sha256:f6a102faf0eb10790147c39f8bc45b2be780dfb26633a56f8bcef4d9d9f048b6 
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DATA_DIR: "/app/data"
      TOR_PROXY_HOST: tor_proxy
      TOR_PROXY_PORT: "9050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "umbrel.local:host-gateway"
    networks:
      - default
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
