version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: mav-bittrack_server_1
      APP_PORT: 8585

  server:
    image: ghcr.io/maverick-2009/bittrack:1.0.0@sha256:5af176f7f18dd659b49c6cfad9672bca9b98b8893e91e7ff59998a343cbab109
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DATA_DIR: "/app/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
